// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/zale144/portpb"
)

// MockClient is an autogenerated mock type for the client type
type MockClient struct {
	mock.Mock
}

// GetPorts provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) GetPorts(ctx context.Context, in *proto.GetPortsReq, opts ...grpc.CallOption) (proto.PortService_GetPortsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 proto.PortService_GetPortsClient
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetPortsReq, ...grpc.CallOption) proto.PortService_GetPortsClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.PortService_GetPortsClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetPortsReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessPortBatch provides a mock function with given fields: ctx, opts
func (_m *MockClient) ProcessPortBatch(ctx context.Context, opts ...grpc.CallOption) (proto.PortService_ProcessPortBatchClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 proto.PortService_ProcessPortBatchClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) proto.PortService_ProcessPortBatchClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.PortService_ProcessPortBatchClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
